### ISSUE TITLE
data.json is not generated correctly

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#1331]
### Description
After update `scully` and `ng-lib`  to version `1.1.1` the `data.json` contains the following string:
```
")[1].split("
```
While the `index.html` in state script contains the correct information and renders the page properly, navigating to the other pages in the running app breaks because it can't get the data from the state.
#### 🔬 Minimal Reproduction
1. Have an application that utilizes `TransferStateService`.
2. Build the app and run scully.
3. Go to dist/static/data.json

I tried it in 2 different projects and it has the same issue.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 11.1.4
Node: 14.16.0
OS: linux x64

Angular: 11.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/ng-lib": "^1.1.1",
"@scullyio/scully": "^1.1.1",
</code></pre>

**Comment by SanderElias** [comment]
@BlindDespair This problem is fixed already. It's happening if you have template strings inside the JSON you're trying to embed.
I'll check if we did release the fix tomorrow.

**Comment by BlindDespair** [comment]
@SanderElias sounds great, thank you for a quick response on the issue!

**Comment by SanderElias** [comment]
@BlindDespair Do you still have this issue? 
We encountered this before, and that turned out to be an issue with the htmlMinimize plugins. (you need to do some settings, but I don't recall which ones)

**Comment by BlindDespair** [comment]
I still have the issue, but I'll check how I can configure the htmlMinimize plugin and see if it helps. I'll post my findings here.

**Comment by BlindDespair** [comment]
@SanderElias I check the configs and what helps is switching off the `minifyJS` option off. 
So here is the difference it produces:
`minifyJS: false,`:
![image](https://user-images.githubusercontent.com/15785773/115962793-42e6f900-a51d-11eb-855e-b82903ac5226.png)
`minifyJS: true,`:
![image](https://user-images.githubusercontent.com/15785773/115962818-6316b800-a51d-11eb-818d-705f9541df6d.png)
and this part is exactly what gets parsed by scully, I guess you can tell why:
![image](https://user-images.githubusercontent.com/15785773/115962835-71fd6a80-a51d-11eb-95f6-9f59682a6a8d.png)
So I am gonna turn it off for now, but I think this has to be solved by default somehow, from what I see, the version with minified inline JS is only 17 bytes smaller which I can easily let go of. I suggest we open an issue on [scully-plugin-minify-html](https://github.com/samvloeberghs/kwerri-oss/tree/master/projects/scully-plugin-minify-html) and suggest to make `minimizeJS: false` as a default, but if you have  a better idea how this can be hanlded better that would interesting to know.

**Comment by SanderElias** [comment]
Yes, the minify plugin does mess up the order of the lines. The script that is injected by Scully is optimized by hand and put in that exact order for a reason. 
During the write-to-disk, the write-to-disk plugin extracts the _first_  string that is inside the `__SCULLY__xxx` markers.
The 17 bytes is probably some white-space, that is put in by the conversion from JSON to the embedded string.
As there is nothing Scully can do about this, I'm going to close the issue. Thanks for reporting back

**Comment by AlonsoK28** [comment]
issue still present using `"scully-plugin-minify-html": "^6.0.0"`

using the following config avoid this isse:

https://scully.io/docs/Reference/plugins/community-plugins/minifyHtml/

```ts
// @ts-ignore
const minifyHtmlOptions: MinifyHtmlOptions = {
  minifyOptions: {
    minifyJS: false
  },
};

setPluginConfig(MinifyHtml, 'render', minifyHtmlOptions);
```
